name: Build

on: push

jobs:
  # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-multi-dimension-matrix
  build_matrix:
    name: Build with gcc
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout with submodules
        # https://github.com/actions/checkout#usage
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Compiler
        # https://github.com/rlalik/setup-cpp-compiler#compiler-selection
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc
      - name: Install cmake
        # https://github.com/lukka/get-cmake#quickstart
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest

      - name: Check gcc
        run: gcc   --version
      - name: Check cmake
        run: cmake --version

      - name: Run cmake
        # Pipe character (|) creates multi-line value here
        run: |
          cd build
          ls -l
          cmake ./..
